export type Establishment = 'Restaurant'
    | 'Cafe'
    | 'Bar'
    | 'Hotel'
    | 'Bakery'
    | 'Butcher'
    | 'Grocery'
    | 'Supermarket'
    | 'Market'
    | 'Farmers Market'
    | 'Food Producer'; 